filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/airflow/logs/**/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"
