apiVersion: apps/v1

kind: Deployment

metadata:
  name: flask-echo-headers-server

spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-echo-headers-server
  template:
    metadata:
      labels:
        app: flask-echo-headers-server
    spec:
      containers:
        - name: web
          image: flask-echo-headers-server:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
