apiVersion: v1

kind: Service

metadata:
  name: flask-echo-headers-service

spec:
  selector:
    app: flask-echo-headers-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: NodePort
